---
- name: Telegram Alerts
  block:
    - name: Telegram Alerts | Send Success Alert
      ansible.builtin.import_tasks: alerts/success_alert.yml
      when:
        - task_failed is not defined

    - name: Telegram Alerts | Send Failure Alert
      ansible.builtin.import_tasks: alerts/failure_alert.yml
      when:
        - task_failed is defined
        - task_failed == true

  rescue:
    - name: Telegram Alerts | Rescue
      ansible.builtin.set_fact:
        task_failed: true
